### ISSUE TITLE
2500 NaN for RPs at ndgf

### ISSUE THREAD

**Issue by inkling16** [CarlColglazier/cheesecake#26]
2500 is currently showing NaN for their mean RPs at Great Northern (ndgf)

![image](https://user-images.githubusercontent.com/5760180/75906823-49944780-5e15-11ea-84c8-871fd9b68be8.png)

**Comment by CarlColglazier** [comment]
Thanks! Looks like frc2500 didn't get any rank points at that event, so the forecast just pretends they don't exist in the future. Simple solution for now is to add 0 points to each team's rank points regardless of match outcome.
